#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso interfaceElsaProperties
wclean libso incompressibleTwoPhaseElsaMixture
wclean libso immiscibleIncompressibleTwoPhaseElsaMixture
wclean libso twoPhaseChangeElsaModel
wclean

